% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={assmt11},
  pdfauthor={MGinorio},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{assmt11}
\author{MGinorio}
\date{11/7/2021}

\begin{document}
\maketitle

\hypertarget{regression-analysis}{%
\subsubsection{Regression Analysis}\label{regression-analysis}}

Using the ``cars'' dataset in R, build a linear model for stopping
distance as a function of speed and replicate the analysis of your
textbook chapter 3 (visualization, quality evaluation of the model, and
residual analysis.)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(moderndive)}
\FunctionTok{library}\NormalTok{(skimr)}
\end{Highlighting}
\end{Shaded}

Let's consider a simple example of how the speed of a car affects its
stopping distance, that is, how far it travels before it comes to a
stop. To examine this relationship, we will use the `cars' dataset.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cars\_regression }\OtherTok{\textless{}{-}}\NormalTok{ cars }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(speed, dist)}

\NormalTok{cars\_regression }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{skim}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\caption{Data summary}\tabularnewline
\toprule
& \\
\midrule
\endfirsthead
\toprule
& \\
\midrule
\endhead
Name & Piped data \\
Number of rows & 50 \\
Number of columns & 2 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Column type frequency: & \\
numeric & 2 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Group variables & None \\
\bottomrule
\end{longtable}

\textbf{Variable type: numeric}

\begin{longtable}[]{@{}lrrrrrrrrrl@{}}
\toprule
skim\_variable & n\_missing & complete\_rate & mean & sd & p0 & p25 &
p50 & p75 & p100 & hist \\
\midrule
\endhead
speed & 0 & 1 & 15.40 & 5.29 & 4 & 12 & 15 & 19 & 25 & ▂▅▇▇▃ \\
dist & 0 & 1 & 42.98 & 25.77 & 2 & 26 & 36 & 56 & 120 & ▅▇▅▂▁ \\
\bottomrule
\end{longtable}

\hypertarget{question}{%
\subsubsection{Question}\label{question}}

How the speed of a car affects its stopping distance, that is, how far
it travels before it comes to a stop?

\hypertarget{eda}{%
\subsubsection{EDA}\label{eda}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\hypertarget{variables}{%
\paragraph{Variables}\label{variables}}

Exploratory analysis of variables

\(y:\) Dependent Variable - \(dist\)

\(\vec{x}\) Independent Variable - \(speed\)

Investigate correlation between this variables

\begin{itemize}
\tightlist
\item
  distance
\item
  speed
\end{itemize}

\includegraphics{Ginorio-Assignment-11_files/figure-latex/eda vars-1.pdf}

\hypertarget{visualize-data}{%
\paragraph{Visualize Data}\label{visualize-data}}

Initial scatterplot of the stopping distance as a function of speed
indicates the stopping distance tends to increase as the speed
increases, as is expected.

The plot does show the relationship is likely linear.

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{Ginorio-Assignment-11_files/figure-latex/vis data-1.pdf}

\hypertarget{create-model}{%
\paragraph{Create Model}\label{create-model}}

The output of the model indicates a linear function as:

\[
stopping\ distance = -17.579 + (3.932 * speed)
\]

A y-intercept of -17.579 does seem peculiar.

Based on the linear model, this would indicate that a car at speeds 0 or
closer to 0 (negative) it would stop in less than 0 feet, which is
accurate since a car that is not in movement thus it does not need to
stop.

The slope of 3.932 based on the speed.

\begin{longtable}[]{@{}lrrrrrr@{}}
\toprule
term & estimate & std\_error & statistic & p\_value & lower\_ci &
upper\_ci \\
\midrule
\endhead
intercept & -17.579 & 6.758 & -2.601 & 0.012 & -35.707 & 0.548 \\
speed & 3.932 & 0.416 & 9.464 & 0.000 & 2.818 & 5.047 \\
\bottomrule
\end{longtable}

\textbf{Coefficient}

also seen under estimate - This portion of the output shows the
estimated coefficient values

\textbf{Std. Error}

For a good model, we typically would like to see a standard error that
is at least five to ten times smaller than the corresponding coefficient

For Example:

the SD error for \(speed\) is 9.45 times smaller then the coefficient
value.(3.932/0.416)

\textbf{P-value}

shows the probability that the corresponding coefficient is not relevant
in the model. This value is also known as the significance or p-value of
the coefficient

The probability that the intercept is not relevant is 0.012.

\begin{verbatim}
## # A tibble: 50 x 5
##       ID  dist speed dist_hat residual
##    <int> <dbl> <dbl>    <dbl>    <dbl>
##  1     1     2     4    -1.85     3.85
##  2     2    10     4    -1.85    11.8 
##  3     3     4     7     9.95    -5.95
##  4     4    22     7     9.95    12.1 
##  5     5    16     8    13.9      2.12
##  6     6    10     9    17.8     -7.81
##  7     7    18    10    21.7     -3.74
##  8     8    26    10    21.7      4.26
##  9     9    34    10    21.7     12.3 
## 10    10    17    11    25.7     -8.68
## # ... with 40 more rows
\end{verbatim}

\textbf{Residuals}

The residuals are the differences between the actual measured values and
the corresponding values on the fitted regression line.

Residual values are normally distributed around a mean of zero in this
case we see that even though the values are not exactly zero we can
still expect a normal distribution.

That is, a good model's residuals should be roughly balanced around and
not too far away from the mean of zero.

\textbf{RSquared \& Residual Standard Error RSE}

These final few lines in the output provide some statistical information
about the quality of the regression model's fit to the data

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(speed\_model)}\SpecialCharTok{$}\NormalTok{r.squared}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.6510794
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(speed\_model)}\SpecialCharTok{$}\NormalTok{sigma}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15.37959
\end{verbatim}

\textbf{Minimum Maximum}

minimum and maximum values of roughly the same magnitude, and first and
third quartile values of roughly the same magnitude.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(speed\_model\_points}\SpecialCharTok{$}\NormalTok{residual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -29.06900  -9.52550  -2.27200  -0.00004   9.21450  43.20100
\end{verbatim}

\textbf{Residual Visual Relationship}

Distribution of Residuals Investigate potential relationships between
the residuals and all explanatory/predictor variables

\textbf{Residual Vs Fitter}

we may be able to construct a model that produces tighter residual
values and better predictions.

Residual values greater than zero mean that the regression model
predicted a value that was too small compared to the actual measured
value, and negative values indicate that the regression model predicted
a value that was too large

\textbf{QQ Plot}

If the residuals were normally distributed, we would expect the points
plotted in this figure to follow a straight line. Which in this case we
do see a straight line forming.

This test could confirm that the speed as a predictor in the model may
be sufficient to explain the data.

\includegraphics{Ginorio-Assignment-11_files/figure-latex/residuals-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(speed\_model)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Ginorio-Assignment-11_files/figure-latex/unnamed-chunk-4-1.pdf}
\includegraphics{Ginorio-Assignment-11_files/figure-latex/unnamed-chunk-4-2.pdf}
\includegraphics{Ginorio-Assignment-11_files/figure-latex/unnamed-chunk-4-3.pdf}
\includegraphics{Ginorio-Assignment-11_files/figure-latex/unnamed-chunk-4-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(speed\_model\_points)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Ginorio-Assignment-11_files/figure-latex/unnamed-chunk-4-5.pdf}

\hypertarget{predictions}{%
\subsubsection{Predictions}\label{predictions}}

We do this so that we can specify that 8 is a value of speed, so that
predict knows how to use it with the model stored in speed\_model

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{predict}\NormalTok{(speed\_model, }\AttributeTok{newdata =} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{speed =} \FunctionTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{, }\DecValTok{21}\NormalTok{, }\DecValTok{50}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##         1         2         3 
##  13.88018  65.00149 179.04134
\end{verbatim}

\(stopping\ distance = -17.579 + (3.932 * speed)\)

\(stopping\ distance = -17.579 + (3.932 * 8)\)

\(stopping\ distance = -17.579 + (3.932 * 21)\)

\(stopping\ distance = -17.579 + (3.932 * 50)\) ** note 50 is out of
range

\hypertarget{conclusion}{%
\subsubsection{Conclusion}\label{conclusion}}

Overall, the car speed would appear to be a good predictor of stopping
distance. The linear regression model does contain some flaws,
particularly in the intercept value and the predictions at higher speeds

\end{document}
